project:
  type: website
  output-dir: docs

website:
  title: "Mariana Martinez - PSCI 3200"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: psci3200qa.qmd
        text: Research Question
      - href: researchd.qmd
        text: Research Design
      - href: researchdesignexpanded.qmd
        text: Research Design Expanded
        
