---
title: "3200 data"
author: "Mariana Martinez"
date: "2026-03-16"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(gapminder)
library(scales)
library(lubridate)
library(gt)
library(gtExtras)
library(readxl)
library(kableExtra)
library(readr)
library(haven)
library(stringr)
```

```{r}
chinese_aid <- read_excel('/Users/mariana/Desktop/PSCI 3200 literature review/datasets/AidDatas_Global_Chinese_Development_Finance_Dataset_Version_3_0/AidDatasGlobalChineseDevelopmentFinanceDataset_v3.0.xlsx', sheet = 5)

head(chinese_aid)
```

```{r}
latam_aid <- chinese_aid %>%
  filter(`Recipient Region` == "America") %>%
  filter(!Recipient %in% c("America, regional", "Curacao", "Sint Maarten (Dutch part)"))
head(latam_aid)
```


```{r}
latam_aid2 <- latam_aid %>%
  
  group_by(Recipient, `Commitment Year`) %>%
  
  summarise(total_finance = sum(`Amount (Constant USD 2021)`, na.rm = T)) 

head(latam_aid2)
```


```{r}
latam_aid3 <- latam_aid2 %>%
  ungroup() %>% 
  #group_by(Recipient) %>%
  mutate(lagged = rollmean(total_finance, 5, fill = NA, align = "right")) %>%
  select(- total_finance) %>%
  rename(country_name = Recipient,
         year = "Commitment Year")

head(latam_aid3)

# left join it with party by country year
```




```{r}
party <- read_csv('/Users/mariana/Desktop/PSCI 3200 literature review/datasets/CPD_V-Party_CSV_v2/V-Dem-CPD-Party-V2.csv')

head(party)
```

```{r}
mod <- party %>%
  select(v2pariglef, v2paanteli, v2panumbseat, v2pavote, v2patotalseat, v2papeople, e_regiongeo, everything()) %>%
  select(1:27) %>%
  select(v2paenname, country_name, year, e_regiongeo, everything()) %>%
  filter(e_regiongeo %in% c(16, 17, 18, 19) & year %in% c(2000:2021)) %>%
  filter(!country_name %in% c("United States of America", "Canada")) %>%
  select(1:9) 
head(mod)
```



```{r}
mod2 <- mod %>%
  group_by(country_name, year) %>%
  summarise(anti_elitism_index = weighted.mean(v2paanteli, w = v2pavote, na.rm =T),
            left_right_index = mean(v2pariglef, w = v2pavote, na.rm = T))

head(mod2)
```

```{r}
master_dataset <- latam_aid3 %>%
  left_join(mod2, by = c("country_name", "year")) %>%
  mutate(log_finance = log1p(lagged))
head(master_dataset)
```

```{r}
summary(master_dataset$lagged)

summary(master_dataset$left_right_index)
```

```{r}
plot_data <- master_dataset %>%
  filter(!is.na(log_finance), !is.na(left_right_index))
```



```{r}
g1 <- ggplot(data = plot_data, aes(x = log_finance, y = left_right_index)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm") +
  labs(
    title = "Chinese Development Finance and Left-Wing Political Support",
    subtitle = "Latin America and the Caribbean (Country-Year Observations)",
    x = "Log of Chinese Development Finance (lagged)",
    y = "Left-Right Ideology Index"
  ) +
  
  theme_classic(base_size = 14) +
  
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12),
    axis.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )
g1
```
```{r}
g2 <- ggplot(data = plot_data, aes(x = log_finance, y = anti_elitism_index)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm") +
  labs(
    title = "Chinese Development Finance and Left-Wing Political Support",
    subtitle = "Latin America and the Caribbean (Country-Year Observations)",
    x = "Log of Chinese Development Finance (lagged)",
    y = "Anti-elitist Ideology Index"
  ) +
  
  theme_classic(base_size = 14) +
  
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12),
    axis.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )
g2
```



