---
title: "expdataset"
author: "Mariana Martinez"
date: "2026-04-11"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(gapminder)
library(scales)
library(lubridate)
library(gt)
library(gtExtras)
library(readxl)
library(kableExtra)
library(readr)
library(haven)
library(stringr)
library(zoo)
library(tidyr)
```
```{r}
party <- read_csv('/Users/mariana/Documents/GitHub/psci3200_marianamartinez/datasets/CPD_V-Party_CSV_v2/V-Dem-CPD-Party-V2.csv')

head(party)
```

```{r}
mod <- party %>%
  select(v2pariglef, v2paanteli, v2panumbseat, v2pavote, v2patotalseat, v2papeople, e_regiongeo, everything()) %>%
  select(1:27) %>%
  select(v2paenname, country_name, year, e_regiongeo, everything()) %>%
  filter(e_regiongeo %in% c(16, 17, 18, 19) & year %in% c(2000:2021)) %>%
  filter(!country_name %in% c("United States of America", "Canada")) %>%
  select(1:9) 
head(mod)
```



```{r}
mod2 <- mod %>%
  group_by(country_name, year) %>%
  summarise(anti_elitism_index = weighted.mean(v2paanteli, w = v2pavote, na.rm =T),
            left_right_index = mean(v2pariglef, w = v2pavote, na.rm = T))

head(mod2)
```

```{r}
mod3 <- mod2 %>%
  group_by(country_name) %>%
  arrange(year) %>%
  complete(year = 2001:2021) %>%
  fill(left_right_index, anti_elitism_index, .direction = "down")
mod3
```

```{r}
# First, I'm looking into a dataset from US development finance corporation
american_aid_untouched <- read_xlsx('/Users/mariana/Documents/GitHub/psci3200_marianamartinez/datasets/AmericanActiveProjects.xlsx')
american_aid_untouched
```

```{r}
american_aid <- american_aid_untouched %>%
  filter(`Fiscal Year` %in% 2000:2021,
         Region == "Western Hem",
         Department != "Insurance",
         Country != "Latin America Regional") %>%
# gonna have to filter by type of aid, department
  group_by(`Fiscal Year`, Country) %>%
  summarise(funding_received = sum(Committed)) %>%
  arrange(Country) %>%
  mutate(Country = str_replace(Country, "Antigua And Barbuda", "Antigua and Barbuda"))
head(american_aid)
```




```{r}
chinese_aid <- read_excel('/Users/mariana/Documents/GitHub/psci3200_marianamartinez/datasets/AidDatas_Global_Chinese_Development_Finance_Dataset_Version_3_0/AidDatasGlobalChineseDevelopmentFinanceDataset_v3.0.xlsx', sheet = 5)

head(chinese_aid)
```
```{r}
latam_aid <- chinese_aid %>%
  filter(`Recipient Region` == "America") %>%
  filter(!Recipient %in% c("America, regional", "Curacao", "Sint Maarten (Dutch part)"))
head(latam_aid)
```


```{r}
latam_aid2 <- latam_aid %>%
  
  group_by(Recipient, `Commitment Year`) %>%
  
  summarise(total_finance = sum(`Amount (Constant USD 2021)`, na.rm = T)) 

head(latam_aid2)
```

```{r}
# checking for stuff that doesn't match if i merge by country
no_match <- latam_aid2 %>% anti_join(american_aid, by = c("Recipient" = "Country"))

unique(no_match$Recipient)
# the countries that don't have matches are Antigua and Barbuda, because they are spelled differently, Bahamas, Barbados, so im going to do a full merge and the ratio for certain countries will be 100% bc its chinese/chinese+american aid--- like what % of aid is chinese respective to american
```

```{r}
american_chinese_aid <- latam_aid2 %>%
  full_join(american_aid, by = c("Recipient" = "Country", "Commitment Year" = "Fiscal Year")) %>%
  rename(chinese_funding = total_finance,
         american_funding = funding_received) %>%
  mutate(american_funding = coalesce(american_funding, 0))
  # mutate(
  #   chinese_funding = log1p(chinese_funding),
  #   american_funding = log1p(american_funding)
  # ) 
#setting both quantities in the log of dollars, now i have to set american funidng as 2021 dollars too

american_chinese_aid
```


```{r}
install.packages("fredr")
library(fredr)

fredr_set_key("1b32afe69f85182f7dab9e135dd1cfce")

cpi <- fredr(series_id = "CPIAUCSL") %>%
  select(date, value)
```

```{r}
cpi <- cpi %>%
  mutate(year = lubridate::year(date)) %>%
  group_by(year) %>%
  summarize(cpi = mean(value))
```

```{r}
american_chinese_aid_inf <- american_chinese_aid %>%
  left_join(cpi, by = c("Commitment Year" = "year"))
```


```{r}
cpi_2021 <- cpi %>% filter(year == 2021) %>% pull(cpi)
```

```{r}
adjusted_funding <- american_chinese_aid_inf %>%
  mutate(
    american_funding_real = american_funding * (cpi_2021 / cpi), 
    chinese_funding_real = chinese_funding,
    chinese_funding_log = log1p(chinese_funding_real),
    american_funding_log = log1p(american_funding_real)
  ) %>%
  select(Recipient, `Commitment Year`, chinese_funding_log, american_funding_log)
#adjusted for 2021 dollars to be in the same unit as chinese and now im gonna log both
adjusted_funding
```



```{r}
# now im going to create the ratio of chinese to total aid received, what fraction of a country's aid in a given year is chinese
ratio_funding <- adjusted_funding %>%
  mutate(chinese_share = chinese_funding_log / (chinese_funding_log + american_funding_log),
         total_aid_log = chinese_funding_log + american_funding_log) %>%
  rename(country_name = Recipient,
         year = `Commitment Year`)
ratio_funding
```


## Now I'm gonna focus on getting data from the IBRD/IDA to have more sustantial info on western loaning

```{r}
wb_raw <- read_excel('/Users/mariana/Documents/GitHub/psci3200_marianamartinez/datasets/IBRD_IDA Summary (Lending).xlsx')
head(wb_raw)
```

```{r}
#grouping by country and year and adding
wb_year_country <- wb_raw %>%
  separate(`Approval Date`, into = c("Month", "day", "year"), sep = "/") %>%
  mutate(year = as.numeric(year)) %>%
  select(-c(Month, day)) %>%
  group_by(Country, year) %>%
  summarise(total_disbursed = sum(`Disbursed, US$`)) %>%
  arrange(Country) %>%
  left_join(cpi, by = "year") %>%
  mutate(wb_funding_real = total_disbursed * (cpi_2021 / cpi),
         logged_wb = log1p(wb_funding_real)) %>%
  select(-c(total_disbursed, cpi, wb_funding_real))
head(wb_year_country)
```

```{r}
western_funding <- adjusted_funding %>%
  left_join(wb_year_country, by = c("Recipient" = "Country", "Commitment Year" = "year")) %>%
  mutate(logged_wb = coalesce(logged_wb, 0),
        chinese_share = chinese_funding_log / (chinese_funding_log + american_funding_log + logged_wb),
         total_aid_log = chinese_funding_log + american_funding_log) %>%
  rename(country_name = Recipient,
         year = `Commitment Year`)
head(western_funding)
```


```{r}
plot_data_final <- western_funding %>%
  inner_join(mod3, by = c("country_name", "year")) %>%
  select(-c(chinese_funding_log, american_funding_log))
# did inner join to make sure that I am having data for everyone
plot_data_final
# so I end up with data from 25 countries to compare

n_distinct(plot_data$country_name)
```




```{r}
excluded <- ratio_funding %>%
  anti_join(mod3, by = c("country_name", "year"))

unique(excluded$country_name)
```

```{r}
left_right <- ggplot(data = plot_data_final, aes(x = chinese_share, y = left_right_index)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm") +
  labs(
    title = "Chinese Development Finance and Left-Wing Political Support",
    subtitle = "Latin America and the Caribbean (Country-Year Observations)",
    x = "Log of Chinese Development Finance (lagged)",
    y = "Left-Right Ideology Index"
  ) +
  
  theme_classic(base_size = 14) +
  
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12),
    axis.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )
left_right
```


```{r}
g2 <- ggplot(data = plot_data_final, aes(x = chinese_share, y = anti_elitism_index)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm") +
  labs(
    title = "Chinese Development Finance and Anti Elitist Rethoric",
    subtitle = "Latin America and the Caribbean (Country-Year Observations)",
    x = "Log of Chinese Development Finance (lagged)",
    y = "Anti-elitist Ideology Index"
  ) +
  
  theme_classic(base_size = 14) +
  
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 12),
    axis.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )
g2
```

## Finally, im gonna account for my controls: GDP per capita and trade with china

```{r}
gdp_wb_raw <- read_csv('/Users/mariana/Documents/GitHub/psci3200_marianamartinez/datasets/GDP WB clean.csv')
head(gdp_wb_raw)
```

```{r}
wb_clean <- gdp_wb_raw %>%
  select(where(~ !all(is.na(.))))

# 3. Keep only relevant columns
wb_clean <- wb_clean %>%
  select(`Country Name`, `Country Code`, starts_with("19"), starts_with("20"))

# 4. Pivot from wide → long
wb_long <- wb_clean %>%
  pivot_longer(
    cols = -c(`Country Name`, `Country Code`),
    names_to = "year",
    values_to = "gdp_pc"
  )

# 5. Clean year + convert types
wb_long <- wb_long %>%
  mutate(
    year = as.numeric(year),
    gdp_pc = as.numeric(gdp_pc)
  )

# 6. Filter years
wb_long <- wb_long %>%
  filter(year >= 2000 & year <= 2021)

# 7. Keep only Latin America & Caribbean countries
latam_codes <- c(
  "ARG","BOL","BRA","CHL","COL","CRI","CUB","DOM","ECU","SLV",
  "GTM","HTI","HND","JAM","MEX","NIC","PAN","PRY","PER","URY","VEN",
  "BLZ","GUY","SUR","TTO"
)

```

```{r}
wb_latam <- wb_long %>%
  filter(`Country Code` %in% latam_codes) %>%
  left_join(cpi, by = "year") %>%
  mutate(gdp_2021dollars = gdp_pc * (cpi_2021 / cpi))
```



```{r}
regression_data <- plot_data_final %>%
  left_join(wb_latam, by = c("country_name" = "Country Name")) %>%
  select(-c(year.y, `Country Code`, gdp_pc, cpi))
head(regression_data)
```

```{r}
install.packages("fixest")   # if not already
library(fixest)
```

```{r}
regression_data <- regression_data %>%
  mutate(
    country = as.factor(country_name),   # or whatever your country var is called
    year = as.numeric(year.x),             # or cyear.y
    log_gdp = log1p(gdp_2021dollars)              # safer than log()
  )
```


```{r}
left_right_re <- feols(
  left_right_index ~ chinese_share + log_gdp | country + year,
  data = regression_data
)

summary(left_right_re)
```

```{r}
anti_e_re <- feols(
  anti_elitism_index ~ chinese_share + log_gdp | country + year,
  data = regression_data
)

summary(anti_e_re)
```
```{r}
unemployment <- read_csv('/Users/mariana/Documents/GitHub/psci3200_marianamartinez/datasets/unemployment.csv')
head(unemployment)
```

```{r}
unem_clean <- unemployment %>%
  select(where(~ !all(is.na(.))))


unem_clean <- unem_clean %>%
  select(`Country Name`, `Country Code`, starts_with("19"), starts_with("20"))


unem_long <- unem_clean %>%
  pivot_longer(
    cols = -c(`Country Name`, `Country Code`),
    names_to = "year",
    values_to = "unemployment rate"
  )


unem_long <- unem_long %>%
  mutate(
    year = as.numeric(year),
    `unemployment rate` = as.numeric(`unemployment rate`)
  )


unem_long <- unem_long %>%
  filter(year >= 2000 & year <= 2021)


latam_codes <- c(
  "ARG","BOL","BRA","CHL","COL","CRI","CUB","DOM","ECU","SLV",
  "GTM","HTI","HND","JAM","MEX","NIC","PAN","PRY","PER","URY","VEN",
  "BLZ","GUY","SUR","TTO"
)
unem_long
```

```{r}
unem_latam <- unem_long %>%
  filter(`Country Code` %in% latam_codes) %>%
  left_join(regression_data, by = c("Country Name" = "country", "year")) 
```

```{r}
model_placebo <- feols(
  `unemployment rate` ~ chinese_share + log_gdp | `Country Name` + year,
  data = unem_latam,
  cluster = ~`Country Name`
)

summary(model_placebo)
```

